In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np 

In [7]:
import numpy as np

s = np.array(5)
print("Scalar s:")
print("ndim:", s.ndim)
print("shape:", s.shape)
print("==========")

v = np.array([1, 2, 3])
print("Vector v:")
print("ndim:", v.ndim)
print("shape:", v.shape)
print("==========")

m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Matrix m:")
print("ndim:", m.ndim)
print("shape:", m.shape)


Scalar s:
ndim: 0
shape: ()
Vector v:
ndim: 1
shape: (3,)
Matrix m:
ndim: 2
shape: (3, 3)


In [8]:
import numpy as np

vec_1 = np.array([1, 2, 3, 4, 5, 6])
mat_1 = vec_1.reshape((3, 2))

print("Vector vec_1:")
print(vec_1)
print("Shape:", vec_1.shape)
print("==========")

print("Matrix mat_1 (reshaped):")
print(mat_1)
print("Shape:", mat_1.shape)


Vector vec_1:
[1 2 3 4 5 6]
Shape: (6,)
Matrix mat_1 (reshaped):
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)


In [9]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2.reshape(vec_2.shape[0],1)
mat_2

array([[1],
       [2],
       [3],
       [4]])

In [10]:
vec_2.shape[0]

4

In [11]:
vec_2[:,None]

array([[1],
       [2],
       [3],
       [4]])

In [12]:
import numpy as np

mat = np.array([
    [False, True, 3.1],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix mat:")
print(mat)
print("Shape:", mat.shape)
print("Data type:", mat.dtype)


Matrix mat:
[[0.  1.  3.1]
 [4.  5.  6. ]
 [7.  8.  9. ]]
Shape: (3, 3)
Data type: float64


In [13]:
class c:
    x = 3
o1 = c()  

In [15]:
mat = np.array([[False,True,"ٌRenad"],
                [4,5,6],
                [7,8,9]
])

print(mat)
print(mat.dtype)

[['False' 'True' 'ٌRenad']
 ['4' '5' '6']
 ['7' '8' '9']]
<U21


In [16]:
mat = np.array([[False,True,"Renad"],
                [4,5,6],
                [7,8,9],
                [0,0,0]
])

mat[1,-2]

np.str_('5')

In [17]:
mat= np.array([[1,6,7,8,2,6],
              [4,1,0,8,3,6],
              [3,6,9,4,5,5]
              ])
mat[-3:-1 , -3:-1]

array([[8, 2],
       [8, 3]])

In [18]:
transpose = mat.T
transpose

array([[1, 4, 3],
       [6, 1, 6],
       [7, 0, 9],
       [8, 8, 4],
       [2, 3, 5],
       [6, 6, 5]])

In [19]:
mat = np.zeros((2,5))
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
mat = np.identity(4,dtype= 'float32')
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [26]:
mat = np.full((3,4),6)

mat

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [28]:
a = ['laila',9,True,'sara']
np.random.choice(a , size = (4,6))

array([['True', 'laila', 'laila', '9', '9', '9'],
       ['9', '9', 'sara', '9', '9', '9'],
       ['True', '9', '9', 'sara', '9', 'True'],
       ['9', 'sara', 'True', 'True', '9', 'sara']], dtype='<U21')